### ISSUE TITLE
item names for pistons in inventory

### ISSUE THREAD

**Issue by uncovery** [Waterflames/Websend#18]
Hi,
I discovered that when someone has a piston or sticky piston in the inventory, websend lists the item as "piston_sticky_base" and "piston_base" instead of "piston" or "sticky_piston". Same goes for "seeds"/"wheat_seeds".

I think this should be changed since the "real" minecraft names do not have the "base" anymore?

**Comment by Waterflames** [comment]
Websend really simply sends the name as reported by the underlying platform with the following code:
`item.put("TypeName", itemStack.getType().name());`
This means that your Bukkit implementation is using piston_base and piston_sticky_base.
I feel like changing this behaviour on the plugin level would result in bad code and unnecessary breaking of existing code by other Websend users.

**Comment by uncovery** [comment]
I don't know how to call the "official" minecraft names that were introduced some 1-2 version ago from MC (those "minecraft:something" ones). 

If minecraft internally uses still old and one ones, I will have to try out all of them then and make a translation table to the official ones then.

**Comment by uncovery** [comment]
So I dug a bit, and figured that you are using the spigot materials list (as seen here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html) where I expected to get the minecraft block/item ids ( as seen here: http://minecraft.gamepedia.com/Data_values/Block_IDs). 

I would consider therefore the issue as closed now that I know what is referenced. It might be helpful in the websend documentation to note that somewhere so people know what is being returned.
