### ISSUE TITLE
Feature Request: Add a "tick" event to WSEvents

### ISSUE THREAD

**Issue by uncovery** [Waterflames/Websend#20]
It would be great to have a "tick" event that occurs every x seconds/ms, configurable in the settings. 
This would allow timers and so on triggered from inside the game with the full Websend information attached.

**Comment by Waterflames** [comment]
Added in Waterflames/WSEvents@4c61acaf4646180d92e860a3df3ba5df80fa1841

**Comment by uncovery** [comment]
Thanks a lot for the quick work on this!
