### ISSUE TITLE
Feature Request: Include more player info for other players in POST info

### ISSUE THREAD

**Issue by uncovery** [Waterflames/Websend#21]
It would be great if the same player info could be inlcuded in the POST info as it is available for the player executing the websend command. Specially location info would be very valuable.

**Comment by Waterflames** [comment]
Added in 0f7917a
Add EXTENDED_PLAYER_DATA=true to your settings file. Note that this can increase the size of the POST request data a lot.

**Comment by uncovery** [comment]
thanks a lot!
