### ISSUE TITLE
Unable to parse localhost URL to plugin

### ISSUE THREAD

**Issue by CeramicTitan** [Waterflames/Websend#24]
http://pastie.org/10816006

P.s pls check bukkit dev pms

**Comment by uncovery** [comment]
What's the config setting for you?
If it's 'localhost/php/minecraft.php', try to change it to 'http://localhost/php/minecraft.php'

**Comment by CeramicTitan** [comment]
@uncovery would you also happen to know about my apache server(xampp) actively refusing to open the socket connection?

**Comment by CeramicTitan** [comment]
using host 127.0.0.1 and still refuses to open socket.

**Comment by uncovery** [comment]
Please paste your complete config.txt here.

**Comment by CeramicTitan** [comment]
@uncovery It was a a brainless moment: I forgot to set the port, however I believe the packet doesn't send? http://pastie.org/10816024

**Comment by uncovery** [comment]
If websend.php reports an error in a specific line, it would make sense if you can show what exactly is in that line.
Are you using the default websend.php?

If so, the error would start here: 
https://github.com/Waterflames/Websend/blob/master/package/Websend.php#L127

**Comment by CeramicTitan** [comment]
hmm I might need to update the websend.php - Im using the one included in the dev.bukkit.org package

**Comment by uncovery** [comment]
Also, please paste your config.txt

**Comment by CeramicTitan** [comment]
@uncovery editted in the above comment :)

**Comment by uncovery** [comment]
Your config points to minecraft.php, but your error is from websend.php?

**Comment by CeramicTitan** [comment]
@uncovery To my understanding, the URL in the config is used for the command to understand send post data to when executing the command(The documentation even states; "URL to send the POST data to when typing a command ingame.") I.e Minecraft.php in this case. As such when running a PHP script to execute code ingame, I believe this is handled through the socket connection and sends custom packets so the server knows how to process the data.

**Comment by uncovery** [comment]
sorry, I am confused a bit. What are you doing then when the error occurs? 
Can you paste the code you are using with the websend class?

**Comment by CeramicTitan** [comment]
@uncovery https://github.com/Waterflames/Websend/blob/master/package/ExternalTimeSet.php The only values changed in this are the parameters parsed(host and port) and the password to match my config.
#
<?php
    require_once 'Websend.php';
    
    $ws = new Websend("127.0.0.1",25565);
    $ws->password = "PutYourPasswordHere";
    
    if($ws->connect()){
        $ws->doCommandAsConsole("time set 6000");
        echo "Time set.";
    }else{
        echo "Failed to connect.";
    }
    $ws->disconnect();
?>
#

**Comment by uncovery** [comment]
leave the port away on that command. change it to
$ws = new Websend("127.0.0.1");

**Comment by CeramicTitan** [comment]
That's the port set in my server.properties.

**Comment by uncovery** [comment]
Yes, and it's wrong to use that in PHP. PHP needs to connect to websend, not to bukkit. PHP is not a minecraft client. websend runs on port 4445, minecraft on 25556

**Comment by CeramicTitan** [comment]
@uncovery So tell me, how does Websend connect to the server?

**Comment by uncovery** [comment]
websend is a plugin of the bukkit server and connects through that to the server. It opens it's own port to accept data from PHP. Did you try already what I asked you to do and remove the port from the command? You do not need to believe me, but since I have a working server here and you do not seem to get it going, maybe you want to it a chance?

**Comment by CeramicTitan** [comment]
Im pretty xampp runs on port 80, Ill give that a go

**Comment by uncovery** [comment]
Port 80 will not work since you will ask PHP to connect to you apache server. You need to connect to the websend plugin which runs by default on port 4445.

You can see that here in the code:
https://github.com/Waterflames/Websend/blob/ced2643883de7f5939a599bd5386af94330b2c69/src/main/java/com/github/websend/Settings.java#L11
If you leave the port away from the command, it will try to connect there.

Either you try whatever you think is right, or you believe someone who knows how this works. Your choice.

**Comment by CeramicTitan** [comment]
...
Warning: fsockopen(): unable to connect to 127.0.0.1:4445 (No connection could be made because the target machine actively refused it. ) in C:\xampp\htdocs\php\Websend.php on line 35
Failed to connect.
Warning: fwrite() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\php\Websend.php on line 74
...

**Comment by uncovery** [comment]
The fact that you get "No connection could be made because the target machine actively refused it." means that something is listening on the other side of that port 4445 but rejects the connection.
It could be your firewall or virus killer? Can you try to disable it for testing?

**Comment by Waterflames** [comment]
"localhost/php/minecraft.php" is not a valid URL.
Use "http://localhost/php/minecraft.php" instead.
